export const LOGIN = '/login'
export const CLASSES = "/classes"
export const STAFF= "/staff"
export const SUBJECTS= "/subjects"
export const FEES = "/fee"
export const STUDENT = "/student"
export const UPLOAD = "/upload"

export const CREATE_TENANT = "/tenant"
export const PROFILE = "/user"
export const ROLES = "/user/roles"
export const PERMISSIONS = "/user/role"
export const CREATE_PARENT = "/user/createParent"
export const GET_PARENTS = "/user/getParents"
export const GET_STUDENT = "/user/students"
export const CREATE_CLASS = "/global/createClass"
export const CREATE_SECTION = "/global/createSection"
export const GET_SECTIONS = "/global/getSections"
export const GET_FEES_BY_CLASS = "/fee/feesByClass";

export const CREATE_DEPARTMENT = "/global/createDepartment"
export const GET_DEPARTMENTS = "/global/getDepartments"
export const GET_DESIGNATIONS = "/global/getDesignations"
export const CREATE_DESIGNATION = "/global/createDesignation"
export const GET_FEE = "/fee"
export const GET_STAFF = "/user/getStaffs"
export const CREATE_STAFF = "/user/createStaff"
export const CREATE_HOSTEL = "/hostel"
export const GET_HOSTELS = "/hostel"
export const GET_HOSTEL_STUDENTS = "/hostel/students"
export const CREATE_ROOM = "/hostel/room"
export const GET_ROOMS = "/hostel/rooms"
export const STUDYHOURS = "/hostel/studyHour"
export const CREATE_STUDYHOURLOG = "/hostel/studyHourLog"
export const FOODMENU = "/hostel/foodmenu"
// export const CREATE_FEES = "/user/createParent"


