export const LOGIN = '/login'
export const CLASSES = '/class'
export const CLASS_CATEGORIES = '/classCategory'
export const STAFF = '/staff'
export const FEES = '/fee'
export const STUDENT = '/student'
export const UPLOAD = '/upload'
export const EXAM = '/exam'
export const NEW_CLASS = '/timetable'
export const TIMETABLE = '/timetable'
export const ACADEMICS = '/academics'
export const TENANT = '/tenant'
export const SECTIONS = '/sections'
export const STUDENT_FEE = '/studentFees'
export const FEE_GROUP = '/feeGroup'
export const ACADEMIC_YEAR = '/academicYear'
export const HOLIDAYS = '/holidays'
export const ATTENDANCE = '/attendance'
export const STAFF_ATTENDANCE = '/staff/attendance'
export const STUDENT_ATTENDANCE = '/student/attendance'
export const PERMISSIONS = '/permissions'
export const ROLES = '/role'
export const MARKS = '/marks'
export const TRANSACTIONS = '/transactions'
export const DESIGNATION = '/designation'
export const BREAKTIME = '/breakTime'
export const SUBJECT = '/subject'
export const ROUTE = '/route'
export const STOPS = '/stops'
export const BRANCH = '/branch'
export const FEE_CATEGORY = '/feeCategory'
export const FEE_SUBCATEGORY = '/feeSubCategory'
export const DASHBOARD = '/dashboard'



